version: '3.4'

services:

  # common

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "pgadmin@example.com"  # Change this to your desired pgAdmin login email
      PGADMIN_DEFAULT_PASSWORD: "password"  # Change this to your desired pgAdmin login password
    ports:
      - "5050:80"  # pgAdmin will be accessible on port 5050 of the host machine
    networks:
      - common-net
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  postgres:
    image: postgres:latest
    ports: 
      - "5432:5432"
    networks:
      - common-net
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data/

networks:
  common-net:
    name: common-net
    driver: bridge

volumes:
  pgadmin_data:  
  postgres_data:
